spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost:3306/clinica_api
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sqp=true

server.error.include-stacktrace=never
api.secret=clinica_api_clave
logging.level.com.clinica.api.infra.security.TokenService=INFO
logging.level.org.springframework.security=INFO




